query Company(
  $id: ID!,
  $developedBefore: String,
  $developedLast: Int,
  $developedAfter: String,
  $publishedBefore: String,
  $publishedLast: Int,
  $publishedAfter: String
) {
  company(id: $id) {
    id
    name
    wikidataId
    developedGames(before: $developedBefore, last: $developedLast, after: $developedAfter) {
      nodes {
        ...gameCardFields
      }
      pageInfo {
        ...paginationFields
      }
    }
    publishedGames(before: $publishedBefore, last: $publishedLast, after: $publishedAfter) {
      nodes {
        ...gameCardFields
      }
      pageInfo {
        ...paginationFields
      }
    }
  }
}
