fragment gameCardFields on Game {
  id
  name
  coverUrl(size: MEDIUM)
  platforms(first: 3) {
    nodes {
      name
    }
    totalCount
  }
  developers(first: 3) {
    nodes {
      name
    }
    totalCount
  }
  isFavorited
}
