query Genre($id: ID!, $before: String, $last: Int, $after: String) {
  genre(id: $id) {
    id
    name
    wikidataId
    games(before: $before, last: $last, after: $after) {
      nodes {
        ...gameCardFields
      }
      pageInfo {
        ...paginationFields
      }
    }
  }
}
