query Stores($before: String, $last: Int, $after: String) {
  stores(before: $before, last: $last, after: $after) {
    nodes {
      id
      name
    }
    pageInfo {
      ...paginationFields
    }
  }
}
