query SteamBlocklist($before: String, $last: Int, $after: String) {
  steamBlocklist(before: $before, last: $last, after: $after) {
    nodes {
      id
      name
      steamAppId
      user {
        username
        slug
      }
      createdAt
    }
    pageInfo {
      ...paginationFields
    }
  }
}
