query SteamBlocklist($cursor: String) {
  steamBlocklist(after: $cursor) {
    nodes {
      id
      name
      steamAppId
      user {
        username
        slug
      }
      createdAt
    }
    pageInfo {
      ...paginationFields
    }
  }
}
