query WikidataBlocklist($before: String, $last: Int, $after: String) {
  wikidataBlocklist(before: $before, last: $last, after: $after) {
    nodes {
      id
      name
      wikidataId
      user {
        username
        slug
      }
      createdAt
    }
    pageInfo {
      ...paginationFields
    }
  }
}
