query WikidataBlocklist($cursor: String) {
  wikidataBlocklist(after: $cursor) {
    nodes {
      id
      name
      wikidataId
      user {
        username
        slug
      }
      createdAt
    }
    pageInfo {
      ...paginationFields
    }
  }
}
