query UserFavorites($userId: ID!, $cursor: String!) {
  user(id: $userId) {
    favoritedGames(after: $cursor) {
      nodes {
        ...gameCardFields
      }
      pageInfo {
        ...paginationFields
      }
    }
  }
}
