query UserFollowing($userId: ID!, $before: String, $last: Int, $after: String) {
  user(id: $userId) {
    following(before: $before, last: $last, after: $after) {
      nodes {
        ...userCardFields
      }
      pageInfo {
        ...paginationFields
      }
    }
  }
}
