query Users($before: String, $last: Int, $after: String, $sortBy: UserSort = null) {
  users(before: $before, last: $last, after: $after, sortBy: $sortBy) {
    nodes {
      ...userCardFields
    }
    pageInfo {
      ...paginationFields
    }
  }
}
