query UserFavorites($userId: ID!, $before: String, $last: Int, $after: String) {
  user(id: $userId) {
    favoritedGames(before: $before, last: $last, after: $after) {
      nodes {
        ...gameCardFields
      }
      pageInfo {
        ...paginationFields
      }
    }
  }
}
