query Games($before: String, $last: Int, $after: String, $sortBy: GameSort, $platformId: ID, $byYear: Int) {
  games(before: $before, last: $last, after: $after, sortBy: $sortBy, onPlatform: $platformId, byYear: $byYear) {
    nodes {
      ...gameCardFields
    }
    pageInfo {
      ...paginationFields
    }
  }
}
