query Games($cursor: String!, $sortBy: GameSort, $platformId: ID, $byYear: Int) {
  games(after: $cursor, sortBy: $sortBy, onPlatform: $platformId, byYear: $byYear) {
    nodes {
      ...gameCardFields
    }
    pageInfo {
      ...paginationFields
    }
  }
}
