query Game($id: ID!) {
  game(id: $id) {
    id
    name
    releaseDate
    coverUrl(size: LARGE)
    avgRating
    genres {
      nodes {
        id
        name
      }
    }
    platforms {
      nodes {
        id
        name
      }
    }
    series {
      id
      name
      # We only use 3, but this provides a buffer in case it returns the game we're looking at right now.
      games(first: 4) {
        nodes {
          id
          name
          coverUrl
        }
      }
    }
    developers {
      nodes {
        id
        name
      }
    }
    publishers {
      nodes {
        id
        name
      }
    }
    engines {
      nodes {
        id
        name
      }
    }
    owners(first: 10) {
      nodes {
        id
        username
        slug
        avatarUrl(size: SMALL)
      }
      totalCount
    }
    favoriters(first: 10) {
      nodes {
        id
        username
        slug
        avatarUrl(size: SMALL)
      }
      totalCount
    }
    wikidataId
    igdbId
    gogId
    steamAppIds
    epicGamesStoreId
    mobygamesId
    pcgamingwikiId
    giantbombId
    isFavorited
    isInLibrary
    gamePurchaseId
  }
}
