query ActivityFeed($feedType: ActivityFeed, $before: String, $last: Int, $after: String) {
  activity(feedType: $feedType, before: $before, last: $last, after: $after) {
    nodes {
      ...eventCardFields
    }
    pageInfo {
      ...paginationFields
    }
  }
}
