query ActivityFeed($feedType: ActivityFeed, $beforeCursor: String, $afterCursor: String) {
  activity(feedType: $feedType, before: $beforeCursor, after: $afterCursor) {
    nodes {
      ...eventCardFields
    }
    pageInfo {
      ...paginationFields
    }
  }
}
