query ActivityFeed($feedType: ActivityFeed) {
  activity(feedType: $feedType) {
    nodes {
      ...eventCardFields
    }
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
  }
}
