query Company($id: ID!) {
  company(id: $id) {
    id
    name
    wikidataId
    developedGames {
      nodes {
        ...gameCardFields
      }
      pageInfo {
        startCursor
        hasNextPage
        hasPreviousPage
      }
    }
    publishedGames {
      nodes {
        ...gameCardFields
      }
      pageInfo {
        startCursor
        hasNextPage
        hasPreviousPage
      }
    }
  }
}
