query GamePurchase($id: ID!) {
  gamePurchase(id: $id) {
    rating
    startDate
    completionDate
    completionStatus
    comments
    hoursPlayed
    replayCount
    platforms {
      nodes {
        id
        name
      }
    }
    stores {
      nodes {
        id
        name
      }
    }
  }
}
