query Games($cursor: String!) {
  games(after: $cursor) {
    nodes {
      id
      name
      releaseDate
      coverUrl(size: MEDIUM)
      platforms(first: 3) {
        nodes {
          name
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
