query Series($id: ID!) {
  series(id: $id) {
    id
    name
    wikidataId
    games {
      nodes {
        ...gameCardFields
      }
      pageInfo {
        startCursor
        hasNextPage
        hasPreviousPage
      }
    }
  }
}
