query UserFollowers($userId: ID!, $cursor: String!) {
  user(id: $userId) {
    followers(after: $cursor) {
      nodes {
        id
        username
        slug
        bio
        avatarUrl(size: MEDIUM)
        privacy
        banned
        role
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
