query Users($cursor: String!) {
  users(after: $cursor) {
    nodes {
      id
      username
      slug
      bio
      avatarUrl(size: MEDIUM)
      privacy
      banned
      role
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
