query UserFollowers($userId: ID!, $cursor: String!) {
  user(id: $userId) {
    followers(after: $cursor) {
      nodes {
        ...userCardFields
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
