query UserFavorites($userId: ID!, $cursor: String!) {
  user(id: $userId) {
    favoritedGames(after: $cursor) {
      nodes {
        id
        name
        coverUrl(size: MEDIUM)
        platforms(first: 3) {
          nodes {
            name
          }
        }
        developers(first: 3) {
          nodes {
            name
          }
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
