name: Test

on: [push]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install
      run: yarn install --frozen-lockfile
    - name: Build
      run: yarn run build
    - name: Test
      run: yarn run test:unit
